endpoints:
   api:
      enabled: true
logging:
   level:
      root: info
ontimize:
   corsfilter:
      enabled: true
   globalcors:
      corsConfigurations:
         '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            exposedHeaders: ["X-Auth-Token","Content-disposition","X-Requested-With"]
            allowedMethods:
            - GET
            - POST
            - PUT
            - OPTIONS
            - DELETE
   jdbc:
      nameConvention: database
      sqlhandler: postgres
      sqlConditionProcessor:
         uppperString: true
         upperLike: true
   security:
      mode: default
      roleInformationService:
         roleRepository: UserRoleDao
         roleNameColumn: ROLE
         serverPermissionQueryId: serverPermissions
         serverPermissionNameColumn: PERMISSION_NAME
         clientPermissionQueryId: clientPermissions
         clientPermissionColumn: XMLCLIENTPERMISSION
      userInformationService:
         userRepository: UserDao
         userLoginColumn: USERNAME
         userPasswordColumn: USER_PASSWORD
         queryId: login
         otherData:
            - USER_FIRST_NAME
            - USER_LAST_NAME
            - USER_EMAIL
            - USER_PICTURE
            - USER_ROLE_ID
            - USER_ID
      userRoleInformationService:
         userRoleRepository: UserRoleDao
         queryId: userRole
         roleLoginColumn: ROLE_ID
         roleNameColumn: ROLE
server:
   port: 33333
   tomcat:
      uri-encoding: UTF-8
   compression:
      enabled: true
      mime-types: application/json, application/xml
spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://45.84.210.174:65432/cd06
      username: cd06
      password: cd06_P4$$!
      initialSize: 10
      testOnBorrow: true
      dbcp2:
         login-timeout:
   main:
      banner-mode: 'off'
   session:
      store-type: none
   autoconfigure:
      exclude: |
         org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration, org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration, org.springframework.boot.autoconfigure.security.FallbackWebSecurityAutoConfiguration
